In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv('data/train.csv')

In [3]:
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0

In [4]:
df['is_toxic'] = (df[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']].sum(axis=1)).astype(int)
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,is_toxic
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,0

In [5]:
df.isna().sum()

id               0
comment_text     0
toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
is_toxic         0
dtype: int64

In [10]:
def is_toxic_bool(x):
    if x > 0:
        return 1
    else:
        return 0

In [11]:
df['is_toxic'] = df['is_toxic'].apply(is_toxic_bool)
df

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,is_toxic
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,0

In [31]:
df.drop(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate'], axis = 1, inplace = True)
df

,id,comment_text,is_toxic,cleaned
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,explanation why the edits made under my userna...
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,d aww he matches this background colour i m se...
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,hey man i m really not trying to edit war it s...
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,more i can t make any real suggestions on impr...
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,you sir are my hero any chance you remember wh...
...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,and for the second time of asking when your vi...
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,you should be ashamed of yourself that is a ho...
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,spitzer umm theres no actual article for prost...
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,and it looks like it was actually you who put ...
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,and i really don t think you understand i came...

In [14]:
class PreProcessor:
    """
    Class containing multiple functions to preprocess text to apply different function to make it better or suitable for more advanced
    applications.
    """
    
    def __init__(self):
        """
        There is not parameters is this function since we did not feel it necessary and instead the function or rather methods are more
        flexible at the time to choose parameters.
        """
        return 
    
    def stemWords(self, sentence):
        '''
        Function to get the stemmed version of a sentence
        '''
        stemmer, tokenizer = PorterStemmer(), TweetTokenizer()
        stemmed_words = [stemmer.stem(w) for w in tokenizer.tokenize(sentence)]
        return " ".join(stemmed_words)
    
    
    def removeNoise(self, string, noise_cars, stop_words = False, W_space = True):
        """
        Function to remove noise from a given string, the noise is the characters that are within the list of noise_cars and also can be 
        stopwords and the function can be configure to replace those stopword for a W that can be useful to know the actual separation among
        words that are not stop words in a string.
        """
        cleaned = string
        
        for char in noise_cars:
            cleaned = cleaned.replace(char,'')
            
        #removing extra spaces
        cleaned = re.sub(' +', ' ', string)
        
        cleaned = cleaned.lower()
        
        #checking whether to delete stop words 
        if stop_words:
            
            stop_words = set(stopwords.words('english'))
            
            for word in stop_words:
                
                #checking to replace the stop words for a W or not
                if W_space:
                    #substituing the stop word for a W, we have spaces before and after the stop word to do get the stop words correctly
                    cleaned = re.sub(' ' + word + ' ',' W ', cleaned)
                    
                else:
                    #substituing the stop word for a W, we have spaces before and after the stop word to do get the stop words correctly
                    cleaned = re.sub(' ' + word + ' ',' ', cleaned)
                    
        #removing extra spaces
        cleaned = re.sub(' +', ' ', string)
                
        
        return cleaned
    
    def clean_string(self, string):
        string = string.replace('\n', ' ')
        string = string.lower()

        string = self.scrub_words(string)
        
        string = self.removeNoise(string, noise_cars = [',', ';'])

        return string
    
    
    def scrub_words(self, text):
        # remove html markup
        text=re.sub("(<.*?>)","",text)

        #remove non-ascii and digits
        text=re.sub("(\\W|\\d)"," ",text)

        #remove whitespace
        text=text.strip()
        return text
    
    def clean_df(self, df, col):
        '''
        Function to clean a given column of a dataframe
        
        ---Input---
        df: dataframe
        col: column to apply the cleaning
        
        
        ---output--- 
        cleaned copy of tha dataframe
        '''
        
        df['cleaned'] = df[col].apply(self.clean_string)
        
        df['cleaned'] = df['cleaned'].apply(self.scrub_words)
        
        return df

In [15]:
cleaner = PreProcessor()

In [16]:
df_clean = cleaner.clean_df(df, 'comment_text')
df_clean.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,is_toxic,cleaned
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,0,explanation why the edits made under my userna...
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,0,d aww he matches this background colour i m se...
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,0,hey man i m really not trying to edit war it s...
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,0,more i can t make any real suggestions on impr...
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,0,you sir are my hero any chance you remember wh...

In [17]:
test_labels = pd.read_csv('data/test_labels.csv')

In [27]:
test_labels

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate,is_toxic
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1,-6
1,0000247867823ef7,-1,-1,-1,-1,-1,-1,-6
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1,-6
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1,-6
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1,-6
...,...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,-1,-1,-1,-1,-1,-1,-6
153160,fffd7a9a6eb32c16,-1,-1,-1,-1,-1,-1,-6
153161,fffda9e8d6fafa9e,-1,-1,-1,-1,-1,-1,-6
153162,fffe8f1340a79fc2,-1,-1,-1,-1,-1,-1,-6
153163,ffffce3fb183ee80,-1,-1,-1,-1,-1,-1,-6

In [26]:
test_labels['is_toxic'] = (test_labels[['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']].sum(axis=1)).astype(int)

In [28]:
test_labels

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate,is_toxic
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1,-6
1,0000247867823ef7,-1,-1,-1,-1,-1,-1,-6
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1,-6
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1,-6
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1,-6
...,...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,-1,-1,-1,-1,-1,-1,-6
153160,fffd7a9a6eb32c16,-1,-1,-1,-1,-1,-1,-6
153161,fffda9e8d6fafa9e,-1,-1,-1,-1,-1,-1,-6
153162,fffe8f1340a79fc2,-1,-1,-1,-1,-1,-1,-6
153163,ffffce3fb183ee80,-1,-1,-1,-1,-1,-1,-6

In [30]:
test_labels['is_toxic'] = test_labels['is_toxic'].apply(is_toxic_bool)
test_labels

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate,is_toxic
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1,0
1,0000247867823ef7,-1,-1,-1,-1,-1,-1,0
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1,0
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1,0
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1,0
...,...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,-1,-1,-1,-1,-1,-1,0
153160,fffd7a9a6eb32c16,-1,-1,-1,-1,-1,-1,0
153161,fffda9e8d6fafa9e,-1,-1,-1,-1,-1,-1,0
153162,fffe8f1340a79fc2,-1,-1,-1,-1,-1,-1,0
153163,ffffce3fb183ee80,-1,-1,-1,-1,-1,-1,0

In [32]:
test_labels.drop(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate'], axis = 1, inplace = True)
test_labels

                      id  is_toxic
0       00001cee341fdb12         0
1       0000247867823ef7         0
2       00013b17ad220c46         0
3       00017563c3f7919a         0
4       00017695ad8997eb         0
...                  ...       ...
153159  fffcd0960ee309b5         0
153160  fffd7a9a6eb32c16         0
153161  fffda9e8d6fafa9e         0
153162  fffe8f1340a79fc2         0
153163  ffffce3fb183ee80         0

[153164 rows x 2 columns]

In [19]:
test_df = pd.read_csv('data/test.csv')

In [20]:
test_df

                      id                                       comment_text
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3       00017563c3f7919a  :If you have a look back at the source, the in...
4       00017695ad8997eb          I don't anonymously edit articles at all.
...                  ...                                                ...
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...

[153164 rows x 2 columns]

In [21]:
test_df_clean = cleaner.clean_df(test_df, 'comment_text')
test_df_clean.head()

,id,comment_text,cleaned
0,00001cee341fdb12,Yo bitch Ja Rule is more succesful then you'll...,yo bitch ja rule is more succesful then you ll...
1,0000247867823ef7,== From RfC == \n\n The title is fine as it is...,from rfc the title is fine as it is imo
2,00013b17ad220c46,""" \n\n == Sources == \n\n * Zawe Ashton on Lap...",sources zawe ashton on lapland
3,00017563c3f7919a,":If you have a look back at the source, the in...",if you have a look back at the source the info...
4,00017695ad8997eb,I don't anonymously edit articles at all.,i don t anonymously edit articles at all